### ISSUE TITLE
TypeError: Object function has no method 'get'

### ISSUE THREAD

**Issue by naconner** [BitGo/lamassu-bitgo#1]
Configured with lamassu-server@1.0.2 on Ubuntu Server 14.04 x64, receiving this error:

```
[2015-01-26T23:52:38.796Z]  INFO: lamassu-server/14454 on lamassu-bitgo: Git: # @
[2015-01-26T23:52:38.846Z] DEBUG: lamassu-server/14454 on lamassu-bitgo: polling for rates (Bitpay)
[2015-01-26T23:52:38.999Z] DEBUG: lamassu-server/14454 on lamassu-bitgo: collecting balance

/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/wallet.js:51
  return bitgo.wallets.get({ walletId: pluginConfig.walletId })
                       ^
TypeError: Object function () {
  if (!this._wallets) {
    this._wallets = new Wallets(this);
  }
  return this._wallets;
} has no method 'get'
    at Object.balance [as transferBalance] (/usr/local/lib/node_modules/lamassu-server/node_modules/lamassu-bitgo/wallet.js:51:24)
    at /usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:524:25
    at /usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:111:13
    at Array.forEach (native)
    at _each (/usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:32:24)
    at Object.async.each (/usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:110:9)
    at _parallel (/usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:523:20)
    at Object.async.parallel (/usr/local/lib/node_modules/lamassu-server/node_modules/async/lib/async.js:539:9)
    at pollBalance (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:318:9)
    at onWalletChange (/usr/local/lib/node_modules/lamassu-server/lib/plugins.js:146:7)
```

**Comment by naconner** [comment]
Resolved with recent commits.
